//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myshop.GlobalResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Myshop.GlobalResource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aadhar No.
        /// </summary>
        public static string AadharNo {
            get {
                return ResourceManager.GetString("AadharNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Action_Login {
            get {
                return ResourceManager.GetString("Action_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete this data. because it&apos;s in use.
        /// </summary>
        public static string AlreadyInUse {
            get {
                return ResourceManager.GetString("AlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is currently under maintainace..
        /// </summary>
        public static string AppUnderMaint {
            get {
                return ResourceManager.GetString("AppUnderMaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This data is auto generated.
        /// </summary>
        public static string AutoGenData {
            get {
                return ResourceManager.GetString("AutoGenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Group.
        /// </summary>
        public static string BloodGroup {
            get {
                return ResourceManager.GetString("BloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Group.
        /// </summary>
        public static string BloodGrp {
            get {
                return ResourceManager.GetString("BloodGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cheque has been issued..
        /// </summary>
        public static string ChequeIssue {
            get {
                return ResourceManager.GetString("ChequeIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Contrller_Login {
            get {
                return ResourceManager.GetString("Contrller_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data deleted successfully.
        /// </summary>
        public static string DataDeleted {
            get {
                return ResourceManager.GetString("DataDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data already exist with same shop name.
        /// </summary>
        public static string DataExistWithSameShopName {
            get {
                return ResourceManager.GetString("DataExistWithSameShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not deleted successfully.
        /// </summary>
        public static string DataNotDeleted {
            get {
                return ResourceManager.GetString("DataNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not saved successfully.
        /// </summary>
        public static string DataNotSaved {
            get {
                return ResourceManager.GetString("DataNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not updated successfully.
        /// </summary>
        public static string DataNotUpdated {
            get {
                return ResourceManager.GetString("DataNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved successfully.
        /// </summary>
        public static string DataSaved {
            get {
                return ResourceManager.GetString("DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data updated successfully.
        /// </summary>
        public static string DataUpdated {
            get {
                return ResourceManager.GetString("DataUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Joining.
        /// </summary>
        public static string DOJ {
            get {
                return ResourceManager.GetString("DOJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Resign.
        /// </summary>
        public static string DOR {
            get {
                return ResourceManager.GetString("DOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Contact No.
        /// </summary>
        public static string EmergContact {
            get {
                return ResourceManager.GetString("EmergContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Image.
        /// </summary>
        public static string EmpImage {
            get {
                return ResourceManager.GetString("EmpImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Role.
        /// </summary>
        public static string EmpRole {
            get {
                return ResourceManager.GetString("EmpRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again after sometime..
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP has been expired.
        /// </summary>
        public static string ExpireOtp {
            get {
                return ResourceManager.GetString("ExpireOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password link has been expired.
        /// </summary>
        public static string ExpireResetLink {
            get {
                return ResourceManager.GetString("ExpireResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Name.
        /// </summary>
        public static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Heading_ChangePassword {
            get {
                return ResourceManager.GetString("Heading_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Heading_Error {
            get {
                return ResourceManager.GetString("Heading_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        public static string Heading_PasswordForget {
            get {
                return ResourceManager.GetString("Heading_PasswordForget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate OTP.
        /// </summary>
        public static string Heading_ValidateOTP {
            get {
                return ResourceManager.GetString("Heading_ValidateOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 Internal Server Error.
        /// </summary>
        public static string HttpStatus_InternalServerError {
            get {
                return ResourceManager.GetString("HttpStatus_InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 Not Found.
        /// </summary>
        public static string HttpStatus_NotFound {
            get {
                return ResourceManager.GetString("HttpStatus_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401 UnAuthorized.
        /// </summary>
        public static string HttpStatus_UnAuthorized {
            get {
                return ResourceManager.GetString("HttpStatus_UnAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong in server..
        /// </summary>
        public static string InternalServerError_500 {
            get {
                return ResourceManager.GetString("InternalServerError_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username/Password is incorrect.
        /// </summary>
        public static string InvalidCredential {
            get {
                return ResourceManager.GetString("InvalidCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format is invalid.
        /// </summary>
        public static string InvalidFileFormat {
            get {
                return ResourceManager.GetString("InvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image height is invalid.
        /// </summary>
        public static string InvalidImageHeight {
            get {
                return ResourceManager.GetString("InvalidImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image width is invalid.
        /// </summary>
        public static string InvalidImageWidth {
            get {
                return ResourceManager.GetString("InvalidImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP is incorrect.
        /// </summary>
        public static string InvalidOtp {
            get {
                return ResourceManager.GetString("InvalidOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Link is invalid.
        /// </summary>
        public static string InvalidResetLink {
            get {
                return ResourceManager.GetString("InvalidResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have tried maximum attempt. now your account is locked.
        /// </summary>
        public static string LoginAttemptExceeded {
            get {
                return ResourceManager.GetString("LoginAttemptExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked. Please contact to administrator..
        /// </summary>
        public static string LoginBlocked {
            get {
                return ResourceManager.GetString("LoginBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not exist.!.
        /// </summary>
        public static string LoginNotExist {
            get {
                return ResourceManager.GetString("LoginNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted files exceeded from specified limit.
        /// </summary>
        public static string MaxFilesLimitExceeded {
            get {
                return ResourceManager.GetString("MaxFilesLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Add Employee.
        /// </summary>
        public static string Module_AddEmployee {
            get {
                return ResourceManager.GetString("Module_AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file posted to the server.
        /// </summary>
        public static string NoFiles {
            get {
                return ResourceManager.GetString("NoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Page in not available.
        /// </summary>
        public static string NotFound_404 {
            get {
                return ResourceManager.GetString("NotFound_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 digit OTP.
        /// </summary>
        public static string Otp4Digit {
            get {
                return ResourceManager.GetString("Otp4Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAN Card No .
        /// </summary>
        public static string PanCard {
            get {
                return ResourceManager.GetString("PanCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string PasswordNew {
            get {
                return ResourceManager.GetString("PasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not matched.
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string PasswordOld {
            get {
                return ResourceManager.GetString("PasswordOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        public static string PasswordSet {
            get {
                return ResourceManager.GetString("PasswordSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN Code.
        /// </summary>
        public static string PINCode {
            get {
                return ResourceManager.GetString("PINCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP has been send on your register mobile no..
        /// </summary>
        public static string SentOTP {
            get {
                return ResourceManager.GetString("SentOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up &amp;rarr;.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size is exceeded.
        /// </summary>
        public static string SizeExceeded {
            get {
                return ResourceManager.GetString("SizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size is too low.
        /// </summary>
        public static string SizeTooLow {
            get {
                return ResourceManager.GetString("SizeTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Work Experience.
        /// </summary>
        public static string TotalExp {
            get {
                return ResourceManager.GetString("TotalExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized. Please login again.
        /// </summary>
        public static string UnAuthorized_401 {
            get {
                return ResourceManager.GetString("UnAuthorized_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is blocked.
        /// </summary>
        public static string UserBlocked {
            get {
                return ResourceManager.GetString("UserBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been deleted.
        /// </summary>
        public static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is inactive.
        /// </summary>
        public static string UserInactive {
            get {
                return ResourceManager.GetString("UserInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is invalid.
        /// </summary>
        public static string UserInvalid {
            get {
                return ResourceManager.GetString("UserInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP validated successfully..
        /// </summary>
        public static string ValidOTP {
            get {
                return ResourceManager.GetString("ValidOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string Value_Resend {
            get {
                return ResourceManager.GetString("Value_Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Value_Validate {
            get {
                return ResourceManager.GetString("Value_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
