//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int Id { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Area { get; set; }
        public string Message { get; set; }
        public string OuterException { get; set; }
        public string InnerException { get; set; }
        public bool IsSync { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsResolved { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Source { get; set; }
        public Nullable<int> ErrorCode { get; set; }
        public string Severity { get; set; }
    }
}
