//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exp_Tr_New
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exp_Tr_New()
        {
            this.Exp_Dtl_New = new HashSet<Exp_Dtl_New>();
        }
    
        public int ExpId { get; set; }
        public int ShopId { get; set; }
        public decimal TotalAmout { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal BalanceAmount { get; set; }
        public int VendorId { get; set; }
        public bool IsCancelled { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public string CancelReason { get; set; }
        public bool IsBalancePaid { get; set; }
        public decimal BalancePaidAmount { get; set; }
        public Nullable<System.DateTime> BalancePaidDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsSync { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int PayModeId { get; set; }
        public string PayModeRefNo { get; set; }
        public Nullable<int> BalPayModeId { get; set; }
        public string BalPayModeRefNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exp_Dtl_New> Exp_Dtl_New { get; set; }
        public virtual Gbl_Master_PayMode Gbl_Master_PayMode { get; set; }
        public virtual Gbl_Master_PayMode Gbl_Master_PayMode1 { get; set; }
        public virtual Gbl_Master_Shop Gbl_Master_Shop { get; set; }
        public virtual Gbl_Master_Vendor Gbl_Master_Vendor { get; set; }
    }
}
