//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exp_Dtl_New
    {
        public int ExpDtlId { get; set; }
        public int ExpTrId { get; set; }
        public int ExpItemId { get; set; }
        public int Qty { get; set; }
        public bool IsCancelled { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public string CancelReason { get; set; }
        public int ShopId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsSync { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Exp_Tr_New Exp_Tr_New { get; set; }
        public virtual Gbl_Master_ExpenseItem Gbl_Master_ExpenseItem { get; set; }
        public virtual Gbl_Master_Shop Gbl_Master_Shop { get; set; }
        public virtual Gbl_Master_User Gbl_Master_User { get; set; }
    }
}
