//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gbl_Master_SubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gbl_Master_SubCategory()
        {
            this.Gbl_Master_Product = new HashSet<Gbl_Master_Product>();
        }
    
        public int SubCatId { get; set; }
        public int CatId { get; set; }
        public int ShopId { get; set; }
        public string SubCatName { get; set; }
        public string Description { get; set; }
        public bool IsSync { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
    
        public virtual Gbl_Master_Category Gbl_Master_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_Product> Gbl_Master_Product { get; set; }
        public virtual Gbl_Master_Shop Gbl_Master_Shop { get; set; }
    }
}
