//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gbl_Master_BankCheque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gbl_Master_BankCheque()
        {
            this.Gbl_Master_BankChequeDetails = new HashSet<Gbl_Master_BankChequeDetails>();
        }
    
        public int ChequeId { get; set; }
        public int BankAccId { get; set; }
        public int ShopId { get; set; }
        public int PageSize { get; set; }
        public int PageStartNo { get; set; }
        public int PageEndNo { get; set; }
        public System.DateTime IssueDate { get; set; }
        public bool IsSync { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public string Description { get; set; }
    
        public virtual Gbl_Master_BankAccount Gbl_Master_BankAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_BankChequeDetails> Gbl_Master_BankChequeDetails { get; set; }
    }
}
