//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gbl_Master_NotificationType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gbl_Master_NotificationType()
        {
            this.Gbl_Master_Notification = new HashSet<Gbl_Master_Notification>();
        }
    
        public int NotificationTypeId { get; set; }
        public string NotificationType { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsSync { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public int ShopId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_Notification> Gbl_Master_Notification { get; set; }
        public virtual Gbl_Master_Shop Gbl_Master_Shop { get; set; }
    }
}
