//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gbl_Master_ExpenseItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gbl_Master_ExpenseItem()
        {
            this.Exp_Dtl_New = new HashSet<Exp_Dtl_New>();
        }
    
        public int Id { get; set; }
        public int ExpTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ShopId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsSync { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal Price { get; set; }
        public int UnitId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exp_Dtl_New> Exp_Dtl_New { get; set; }
        public virtual Gbl_Master_ExpenseType Gbl_Master_ExpenseType { get; set; }
        public virtual Gbl_Master_Shop Gbl_Master_Shop { get; set; }
        public virtual Gbl_Master_Unit Gbl_Master_Unit { get; set; }
    }
}
