//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gbl_Master_Task
    {
        public int TaskId { get; set; }
        public string TaskDetails { get; set; }
        public byte Priority { get; set; }
        public bool IsImportant { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public bool IsSync { get; set; }
        public bool IsDeleted { get; set; }
        public int ShopId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public int AssignedUserId { get; set; }
    
        public virtual Gbl_Master_Shop Gbl_Master_Shop { get; set; }
        public virtual Gbl_Master_User Gbl_Master_User { get; set; }
        public virtual Gbl_Master_User Gbl_Master_User1 { get; set; }
    }
}
