//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gbl_Master_User_Permission
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int PageId { get; set; }
        public bool IsBlockAccess { get; set; }
        public bool Read { get; set; }
        public bool Write { get; set; }
        public bool Delete { get; set; }
        public bool Update { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public int CreationBy { get; set; }
        public int ModifiedBy { get; set; }
        public bool IsSync { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Gbl_Master_Page Gbl_Master_Page { get; set; }
        public virtual Gbl_Master_User Gbl_Master_User { get; set; }
    }
}
