//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gbl_Master_Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gbl_Master_Shop()
        {
            this.Exp_Dtl_New = new HashSet<Exp_Dtl_New>();
            this.Exp_Tr_New = new HashSet<Exp_Tr_New>();
            this.Gbl_Master_Bank = new HashSet<Gbl_Master_Bank>();
            this.Gbl_Master_BankAccount = new HashSet<Gbl_Master_BankAccount>();
            this.Gbl_Master_BankAccount1 = new HashSet<Gbl_Master_BankAccount>();
            this.Gbl_Master_BankChequeDetails = new HashSet<Gbl_Master_BankChequeDetails>();
            this.Gbl_Master_Brand = new HashSet<Gbl_Master_Brand>();
            this.Gbl_Master_Category = new HashSet<Gbl_Master_Category>();
            this.Gbl_Master_ExpenseItem = new HashSet<Gbl_Master_ExpenseItem>();
            this.Gbl_Master_ExpenseType = new HashSet<Gbl_Master_ExpenseType>();
            this.Gbl_Master_Notification = new HashSet<Gbl_Master_Notification>();
            this.Gbl_Master_NotificationType = new HashSet<Gbl_Master_NotificationType>();
            this.Gbl_Master_PayMode = new HashSet<Gbl_Master_PayMode>();
            this.Gbl_Master_Product = new HashSet<Gbl_Master_Product>();
            this.Gbl_Master_Task = new HashSet<Gbl_Master_Task>();
            this.Gbl_Master_User = new HashSet<Gbl_Master_User>();
            this.Gbl_Master_Vendor = new HashSet<Gbl_Master_Vendor>();
            this.Gbl_Master_SubCategory = new HashSet<Gbl_Master_SubCategory>();
            this.MasterVendors = new HashSet<MasterVendor>();
            this.Sale_Dtl_Invoice = new HashSet<Sale_Dtl_Invoice>();
            this.Sale_Setting = new HashSet<Sale_Setting>();
            this.Sale_Tr_Invoice = new HashSet<Sale_Tr_Invoice>();
            this.Stk_Tr_Entry = new HashSet<Stk_Tr_Entry>();
            this.Stk_Dtl_Entry = new HashSet<Stk_Dtl_Entry>();
            this.UserShopMappers = new HashSet<UserShopMapper>();
        }
    
        public int ShopId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public int Distict { get; set; }
        public int State { get; set; }
        public int Owner { get; set; }
        public string GSTIN { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsSync { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public bool IsPrimary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exp_Dtl_New> Exp_Dtl_New { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exp_Tr_New> Exp_Tr_New { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_Bank> Gbl_Master_Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_BankAccount> Gbl_Master_BankAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_BankAccount> Gbl_Master_BankAccount1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_BankChequeDetails> Gbl_Master_BankChequeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_Brand> Gbl_Master_Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_Category> Gbl_Master_Category { get; set; }
        public virtual Gbl_Master_City Gbl_Master_City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_ExpenseItem> Gbl_Master_ExpenseItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_ExpenseType> Gbl_Master_ExpenseType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_Notification> Gbl_Master_Notification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_NotificationType> Gbl_Master_NotificationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_PayMode> Gbl_Master_PayMode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_Product> Gbl_Master_Product { get; set; }
        public virtual Gbl_Master_State Gbl_Master_State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_Task> Gbl_Master_Task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_User> Gbl_Master_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_Vendor> Gbl_Master_Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_SubCategory> Gbl_Master_SubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterVendor> MasterVendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale_Dtl_Invoice> Sale_Dtl_Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale_Setting> Sale_Setting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale_Tr_Invoice> Sale_Tr_Invoice { get; set; }
        public virtual Gbl_Master_User Gbl_Master_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stk_Tr_Entry> Stk_Tr_Entry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stk_Dtl_Entry> Stk_Dtl_Entry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserShopMapper> UserShopMappers { get; set; }
    }
}
