//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gbl_Attachment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gbl_Attachment()
        {
            this.Gbl_Master_Employee = new HashSet<Gbl_Master_Employee>();
            this.Gbl_Master_Employee1 = new HashSet<Gbl_Master_Employee>();
            this.Gbl_Master_Employee2 = new HashSet<Gbl_Master_Employee>();
        }
    
        public int AttachmentId { get; set; }
        public string FleName { get; set; }
        public string OriginalFileName { get; set; }
        public string FileExtension { get; set; }
        public string ModuleName { get; set; }
        public byte[] Attachment { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public int ModifiedBy { get; set; }
        public int ShopId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public string FileName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_Employee> Gbl_Master_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_Employee> Gbl_Master_Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_Employee> Gbl_Master_Employee2 { get; set; }
    }
}
