//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gbl_Master_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gbl_Master_Product()
        {
            this.Stk_Dtl_Entry = new HashSet<Stk_Dtl_Entry>();
        }
    
        public int ProductId { get; set; }
        public int SubCatId { get; set; }
        public int ShopId { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public decimal MinQuantity { get; set; }
        public string ProductCode { get; set; }
        public int UnitId { get; set; }
        public bool IsSync { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
    
        public virtual Gbl_Master_Unit Gbl_Master_Unit { get; set; }
        public virtual Gbl_Master_SubCategory Gbl_Master_SubCategory { get; set; }
        public virtual Gbl_Master_Shop Gbl_Master_Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stk_Dtl_Entry> Stk_Dtl_Entry { get; set; }
    }
}
