//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gbl_Master_Page
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gbl_Master_Page()
        {
            this.Gbl_Master_User_Permission = new HashSet<Gbl_Master_User_Permission>();
        }
    
        public int PageId { get; set; }
        public int ModuleId { get; set; }
        public int ParentId { get; set; }
        public string PageName { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public bool IsSync { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Gbl_Master_AppModule Gbl_Master_AppModule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_User_Permission> Gbl_Master_User_Permission { get; set; }
    }
}
