//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gbl_Master_BankAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gbl_Master_BankAccount()
        {
            this.Gbl_Master_BankCheque = new HashSet<Gbl_Master_BankCheque>();
            this.Stk_Tr_Entry = new HashSet<Stk_Tr_Entry>();
        }
    
        public int BankAccId { get; set; }
        public int BankId { get; set; }
        public int AccTypeId { get; set; }
        public int ShopId { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public string BranchName { get; set; }
        public string BranchIFSC { get; set; }
        public string BranchAddress { get; set; }
        public bool IsSync { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public string AccHolderName { get; set; }
    
        public virtual Gbl_Master_Bank Gbl_Master_Bank { get; set; }
        public virtual Gbl_Master_BankAccountType Gbl_Master_BankAccountType { get; set; }
        public virtual Gbl_Master_Shop Gbl_Master_Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gbl_Master_BankCheque> Gbl_Master_BankCheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stk_Tr_Entry> Stk_Tr_Entry { get; set; }
    }
}
