//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime LoginDate { get; set; }
        public int LoginAttempt { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsSync { get; set; }
        public Nullable<bool> IsReset { get; set; }
        public bool IsLoginBlocked { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public string OTPid { get; set; }
        public Nullable<System.DateTime> ReserExpireTime { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public int CreationBy { get; set; }
        public int ModifiedBy { get; set; }
    
        public virtual Gbl_Master_User Gbl_Master_User { get; set; }
    }
}
