//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyshopDb : DbContext
    {
        public MyshopDb()
            : base("name=MyshopDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<Gbl_AppDowntime> Gbl_AppDowntime { get; set; }
        public virtual DbSet<Gbl_Attachment> Gbl_Attachment { get; set; }
        public virtual DbSet<Gbl_Master_AppModule> Gbl_Master_AppModule { get; set; }
        public virtual DbSet<Gbl_Master_Bank> Gbl_Master_Bank { get; set; }
        public virtual DbSet<Gbl_Master_BankAccount> Gbl_Master_BankAccount { get; set; }
        public virtual DbSet<Gbl_Master_BankAccountType> Gbl_Master_BankAccountType { get; set; }
        public virtual DbSet<Gbl_Master_BankCheque> Gbl_Master_BankCheque { get; set; }
        public virtual DbSet<Gbl_Master_BankChequeDetails> Gbl_Master_BankChequeDetails { get; set; }
        public virtual DbSet<Gbl_Master_Brand> Gbl_Master_Brand { get; set; }
        public virtual DbSet<Gbl_Master_Category> Gbl_Master_Category { get; set; }
        public virtual DbSet<Gbl_Master_City> Gbl_Master_City { get; set; }
        public virtual DbSet<Gbl_Master_Customer> Gbl_Master_Customer { get; set; }
        public virtual DbSet<Gbl_Master_CustomerType> Gbl_Master_CustomerType { get; set; }
        public virtual DbSet<Gbl_Master_DocProof> Gbl_Master_DocProof { get; set; }
        public virtual DbSet<Gbl_Master_DocProofType> Gbl_Master_DocProofType { get; set; }
        public virtual DbSet<Gbl_Master_Employee> Gbl_Master_Employee { get; set; }
        public virtual DbSet<Gbl_Master_Employee_Role> Gbl_Master_Employee_Role { get; set; }
        public virtual DbSet<Gbl_Master_Notification> Gbl_Master_Notification { get; set; }
        public virtual DbSet<Gbl_Master_NotificationType> Gbl_Master_NotificationType { get; set; }
        public virtual DbSet<Gbl_Master_Page> Gbl_Master_Page { get; set; }
        public virtual DbSet<Gbl_Master_PayMode> Gbl_Master_PayMode { get; set; }
        public virtual DbSet<Gbl_Master_Product> Gbl_Master_Product { get; set; }
        public virtual DbSet<Gbl_Master_Shop> Gbl_Master_Shop { get; set; }
        public virtual DbSet<Gbl_Master_State> Gbl_Master_State { get; set; }
        public virtual DbSet<Gbl_Master_SubCategory> Gbl_Master_SubCategory { get; set; }
        public virtual DbSet<Gbl_Master_Task> Gbl_Master_Task { get; set; }
        public virtual DbSet<Gbl_Master_Unit> Gbl_Master_Unit { get; set; }
        public virtual DbSet<Gbl_Master_User> Gbl_Master_User { get; set; }
        public virtual DbSet<Gbl_Master_User_Permission> Gbl_Master_User_Permission { get; set; }
        public virtual DbSet<Gbl_Master_UserType> Gbl_Master_UserType { get; set; }
        public virtual DbSet<Gbl_Master_Vendor> Gbl_Master_Vendor { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<MasterVendor> MasterVendors { get; set; }
        public virtual DbSet<Sale_Dtl_Invoice> Sale_Dtl_Invoice { get; set; }
        public virtual DbSet<Sale_Tr_Invoice> Sale_Tr_Invoice { get; set; }
        public virtual DbSet<Stk_Dtl_Entry> Stk_Dtl_Entry { get; set; }
        public virtual DbSet<Stk_Tr_Entry> Stk_Tr_Entry { get; set; }
        public virtual DbSet<User_ShopMapper> User_ShopMapper { get; set; }
        public virtual DbSet<UserShopMapper> UserShopMappers { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    
        [DbFunction("MyshopDb", "ss")]
        public virtual IQueryable<ss_Result> ss(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ss_Result>("[MyshopDb].[ss](@id)", idParameter);
        }
    
        public virtual ObjectResult<SpGetEmpList_Result> SpGetEmpList(Nullable<int> pageNo, Nullable<int> pageSize, Nullable<int> shopId)
        {
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var shopIdParameter = shopId.HasValue ?
                new ObjectParameter("ShopId", shopId) :
                new ObjectParameter("ShopId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpGetEmpList_Result>("SpGetEmpList", pageNoParameter, pageSizeParameter, shopIdParameter);
        }
    }
}
