//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_Dtl_Invoice
    {
        public int InvoiceDetailId { get; set; }
        public int InvoiceId { get; set; }
        public int ProductId { get; set; }
        public int Qty { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsReturn { get; set; }
        public Nullable<int> ReturnQty { get; set; }
        public Nullable<decimal> ReturnAmount { get; set; }
        public string ReturnRemark { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public bool IsDeleted { get; set; }
        public int ShopId { get; set; }
        public bool IsSync { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Gbl_Master_Product Gbl_Master_Product { get; set; }
        public virtual Gbl_Master_Shop Gbl_Master_Shop { get; set; }
        public virtual Sale_Tr_Invoice Sale_Tr_Invoice { get; set; }
    }
}
