//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stk_Tr_Entry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stk_Tr_Entry()
        {
            this.Stk_Dtl_Entry = new HashSet<Stk_Dtl_Entry>();
        }
    
        public int Id { get; set; }
        public int VendorId { get; set; }
        public int ShopId { get; set; }
        public int PayModeId { get; set; }
        public Nullable<int> DebitAccount { get; set; }
        public string VendorReceiptNo { get; set; }
        public string ShopReceiptEntryNo { get; set; }
        public Nullable<int> ChequePageId { get; set; }
        public decimal TotalAmt { get; set; }
        public Nullable<decimal> AdditionalAmt { get; set; }
        public decimal PaidAmt { get; set; }
        public decimal RemainingAmt { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public bool IsSync { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
    
        public virtual Gbl_Master_BankAccount Gbl_Master_BankAccount { get; set; }
        public virtual Gbl_Master_BankChequeDetails Gbl_Master_BankChequeDetails { get; set; }
        public virtual Gbl_Master_Shop Gbl_Master_Shop { get; set; }
        public virtual MasterVendor MasterVendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stk_Dtl_Entry> Stk_Dtl_Entry { get; set; }
    }
}
