//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stk_Dtl_Entry
    {
        public int StockTrId { get; set; }
        public int StockMstId { get; set; }
        public int ProductId { get; set; }
        public int ShopId { get; set; }
        public int BrandId { get; set; }
        public decimal SellPrice { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal Qty { get; set; }
        public string Color { get; set; }
        public string Description { get; set; }
        public bool IsSync { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public int ModifiedBy { get; set; }
    
        public virtual Gbl_Master_Brand Gbl_Master_Brand { get; set; }
        public virtual Gbl_Master_Product Gbl_Master_Product { get; set; }
        public virtual Gbl_Master_Shop Gbl_Master_Shop { get; set; }
        public virtual Stk_Tr_Entry Stk_Tr_Entry { get; set; }
    }
}
