//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserShopMapper
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ShopId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public int CreationBy { get; set; }
        public int ModifiedBy { get; set; }
        public bool IsSync { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Gbl_Master_Shop Gbl_Master_Shop { get; set; }
        public virtual Gbl_Master_User Gbl_Master_User { get; set; }
    }
}
